CREATE TABLE t_p62094557_heroes_browser_game.heroes (
    id SERIAL PRIMARY KEY,
    user_id VARCHAR(64) NOT NULL UNIQUE,
    name VARCHAR(64) NOT NULL DEFAULT 'Странник',
    level INTEGER NOT NULL DEFAULT 1,
    xp INTEGER NOT NULL DEFAULT 0,
    xp_next INTEGER NOT NULL DEFAULT 300,
    hp INTEGER NOT NULL DEFAULT 100,
    max_hp INTEGER NOT NULL DEFAULT 100,
    gold INTEGER NOT NULL DEFAULT 250,
    silver INTEGER NOT NULL DEFAULT 480,
    gems INTEGER NOT NULL DEFAULT 5,
    glory INTEGER NOT NULL DEFAULT 0,
    attack INTEGER NOT NULL DEFAULT 12,
    defense INTEGER NOT NULL DEFAULT 8,
    magic INTEGER NOT NULL DEFAULT 6,
    speed INTEGER NOT NULL DEFAULT 10,
    stat_strength INTEGER NOT NULL DEFAULT 5,
    stat_defense INTEGER NOT NULL DEFAULT 5,
    stat_agility INTEGER NOT NULL DEFAULT 5,
    stat_mastery INTEGER NOT NULL DEFAULT 5,
    stat_vitality INTEGER NOT NULL DEFAULT 5,
    battles INTEGER NOT NULL DEFAULT 6,
    battles_last_regen_at TIMESTAMPTZ,
    campaign_end_at TIMESTAMPTZ,
    campaign_reward INTEGER NOT NULL DEFAULT 0,
    location VARCHAR(64) NOT NULL DEFAULT 'Поселок',
    quest_progress JSONB NOT NULL DEFAULT '{}',
    quest_claimed JSONB NOT NULL DEFAULT '{}',
    total_silver_earned INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_heroes_user_id ON t_p62094557_heroes_browser_game.heroes(user_id);
